### ISSUE TITLE
Gitlab Page Not Accessible (Private?)

### ISSUE THREAD

**Issue by Shelnutt2** [trendzetter/VegetableGardenPlanner#2]
When trying to view the gitlab page, its 404'ing. I'm guessing the [Gitlab repo](https://gitlab.com/Trendzetter/VegetableGardenPlanner) is not set to public?

**Comment by trendzetter** [comment]
OOOPPSSS!!

**Comment by trendzetter** [comment]
Thanks for pointing out.

**Comment by trendzetter** [comment]
Should be OK now
